### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Ingvarr71** [ExtendedReborn/android_manifest#9]
Hello! When assembling the firmware for Xiaomi Redmi Note 6 Pro, I get this error. How do I fix it?

[ 99% 580/581] finishing build rules ...
FAILED: 
hardware/qcom-caf/msm8998/audio/hal/Android.mk: error: "audio.primary.sdm660 (SHARED_LIBRARIES android-arm64) missing android.hardware.power-ndk_platform (SHARED_LIBRARIES android-arm64)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
hardware/qcom-caf/msm8998/audio/hal/Android.mk: error: "audio.primary.sdm660 (SHARED_LIBRARIES android-arm) missing android.hardware.power-ndk_platform (SHARED_LIBRARIES android-arm)" 
You can set ALLOW_MISSING_DEPENDENCIES=true in your environment if this is intentional, but that may defer real problems until later in the build.
build/make/core/main.mk:1121: error: exiting from previous errors.
01:13:41 ckati failed with: exit status 1

**Comment by THERAD1** [comment]
Add V1 just before ndk...android.hardware.power-V1-ndk_platform
